DATA BRINQUEDOS;
LENGTH NOME $ 30. FABRICANTE $ 30. IDADE 3.;
INFILE DATALINES DLM=',';
INPUT NOME $ FABRICANTE $ IDADE;
DATALINES;
BONECA,GAUSSIAN,5
QUEBRA, GAUSSIAN,7
KIT, PROBA, 5
GAME, GAUSSIAN, 7
KIT2, PROBA, 10
URSO,PROBA, 5
LIVRO,GAUSSIAN, 10
;
RUN;

/* FABRICANTE */
PROC FREQ DATA=BRINQUEDOS;
TABLES FABRICANTE ;
TITLE 'FABRICANTE';
RUN;

/* FABRICANTE */
PROC FREQ DATA=BRINQUEDOS;
TABLE FABRICANTE ;
TITLE 'FABRICANTE TABLE';
RUN;
/* SEM TABLE */
PROC FREQ DATA=BRINQUEDOS;
TITLE 'FABRICANTE SEM TABLE';
RUN;

/* CRUZADA BI DIMENSIONAL*/
PROC FREQ DATA=BRINQUEDOS;
TABLES FABRICANTE * IDADE;
TITLE 'CRUZADA ENTRE FABRICANTE E IDADE';
RUN;
